##########################################################################
# File: dktool/cmake/scripts/dkml/workflow/compilers-github-workflows-dkml.in.yml#
#                                                                        #
# Copyright 2022 Diskuv, Inc.                                            #
#                                                                        #
# Licensed under the Apache License, Version 2.0 (the "License");        #
# you may not use this file except in compliance with the License.       #
# You may obtain a copy of the License at                                #
#                                                                        #
#     http://www.apache.org/licenses/LICENSE-2.0                         #
#                                                                        #
# Unless required by applicable law or agreed to in writing, software    #
# distributed under the License is distributed on an "AS IS" BASIS,      #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        #
# implied. See the License for the specific language governing           #
# permissions and limitations under the License.                         #
#                                                                        #
##########################################################################

# Updating
# --------
#
# 1. Delete this file.
# 2. Run dk with your original arguments:
#        ./dk dkml.workflow.compilers CI GitHub Desktop OS Windows
#    or get help to come up with new arguments:
#        ./dk dkml.workflow.compilers HELP

name: Build with DkML compiler

on:
  # trigger on any push or pull request
  push:
  pull_request:
  # ... or trigger manually from GitHub web interface
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include: #
          - gh_os: windows-2019
            abi_pattern: win32-windows_x86
            dkml_host_abi: windows_x86
          - gh_os: windows-2019
            abi_pattern: win32-windows_x86_64
            dkml_host_abi: windows_x86_64

    runs-on: ${{ matrix.gh_os }}
    name: build / ${{ matrix.abi_pattern }}

    # mirage-crypto does not support MSVC as of 2023-09-03. Remove
    # this when MSVC is properly supported.
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache DkML compilers code
        uses: actions/cache@v3
        id: cache-dkml-compilers
        with:
          path: .ci/dkml-compilers
          key: ${{ runner.os }}

      - name: Checkout DkML compilers code
        if: steps.cache-dkml-compilers.outputs.cache-hit != 'true'
        # For help: ./dk dkml.workflow.compilers HELP
        run: ./dk dkml.workflow.compilers CI GitHub

      # The .ci/dkml-compilers "pre" actions will create the environment variables:
      #   opam_root, exe_ext, dkml_host_abi, abi_pattern (and many more)
      #
      - name: Setup DkML compilers on a Windows host
        if: startsWith(matrix.dkml_host_abi, 'windows_')
        uses: ./.ci/dkml-compilers/gh-windows/pre
        with:
          DKML_COMPILER: ${{ env.DKML_COMPILER }}
          CACHE_PREFIX: ${{ env.CACHE_PREFIX }}

      # This section is for your own build logic which you should place in
      # ci/build-test.sh or a similar file

      - name: Build and test on Windows host
        if: startsWith(matrix.dkml_host_abi, 'windows_')
        shell: msys2 {0}
        run: ci/build-test.sh

      - name: Build and test on non-Windows host
        if: "!startsWith(matrix.dkml_host_abi, 'windows_')"
        run: ci/build-test.sh

      # The .ci/dkml-compilers "post" actions will finalize caching, etc.

      - name: Teardown DkML compilers on a Windows host
        if: startsWith(matrix.dkml_host_abi, 'windows_')
        uses: ./.ci/dkml-compilers/gh-windows/post

      - name: Teardown DkML compilers on a Darwin host
        if: startsWith(matrix.dkml_host_abi, 'darwin_')
        uses: ./.ci/dkml-compilers/gh-darwin/post

      - name: Teardown DkML compilers on a Linux host
        if: startsWith(matrix.dkml_host_abi, 'linux_')
        uses: ./.ci/dkml-compilers/gh-linux/post
